### ISSUE TITLE
Comex issue with NGA_Put64

### ISSUE THREAD

**Issue by ajmay81** [GlobalArrays/ga#48]
When using `NGA_Put64` there are problems if the values are over the 32-bit limit, i.e. they cannot be represented by `int`, .eg. see the seg fault below. Even though `_my_memcpy` takes a `size_t n`, it's passed `int bytes` so at least by that point we've lost the 64-bit information. Everything works fine for a non-Comex port, eg. --with-sockets.

    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff54fb254 in __memcpy_sse2_unaligned () from /lib64/libc.so.6
    (gdb) where
    #0  0x00007ffff54fb254 in __memcpy_sse2_unaligned () from /lib64/libc.so.6
    #1  0x000000000395f222 in _my_memcpy (dest=0x7ffdb6c6f010, src=0x7ffed4e23010, n=18446744071562067968) at src-mpi/comex.c:139
    #2  0x000000000395ff72 in _put_nbi (src=0x7ffed4e23010, dst=0x7ffdb6c6f010, bytes=-2147483648, proc=0) at src-mpi/comex.c:644
    #3  0x000000000395fe48 in comex_put (src=0x7ffed4e23010, dst=0x7ffdb6c6f010, bytes=-2147483648, proc=0, group=0) at src-mpi/comex.c:613
    #4  0x000000000395b94e in PARMCI_PutS (src_ptr=0x7ffed4e23010, src_stride_arr=0x7fffffffc824, dst_ptr=0x7ffdb6c6f010, dst_stride_arr=0x7fffffffc844, count=0x7fffffffc804, stride_levels=0, proc=0) at src-armci/armci.c:484
    #5  0x000000000395e889 in ARMCI_PutS (src_ptr=0x7ffed4e23010, src_stride_arr=0x7fffffffc824, dst_ptr=0x7ffdb6c6f010, dst_stride_arr=0x7fffffffc844, count=0x7fffffffc804, stride_levels=0, proc=0) at src-armci/capi.c:377
    #6  0x00000000038d8a76 in ngai_puts (loc_base_ptr=0x7ffed4e23010 "", pbuf=0x7ffed4e23010 "", stride_loc=0x7fffffffc824, prem=0x7ffdb6c6f010 "", stride_rem=0x7fffffffc844, count=0x7fffffffc804, nstrides=0, proc=0, field_off=0, field_size=-1, type_size=8)
    at global/src/onesided.c:411
    #7  0x00000000038db979 in ngai_put_common (g_a=-1000, lo=0x7fffffffcd90, hi=0x7fffffffcd50, buf=0x7ffed4e23010, ld=0x7fffffffcd10, field_off=0, field_size=-1, nbhandle=0x0) at global/src/onesided.c:708
    #8  0x00000000038dea0e in pnga_put (g_a=-1000, lo=0x7fffffffcd90, hi=0x7fffffffcd50, buf=0x7ffed4e23010, ld=0x7fffffffcd10) at global/src/onesided.c:1265
    #9  0x00000000038674df in NGA_Put64 (g_a=-1000, lo=0x30901270, hi=0x309017b0, buf=0x7ffed4e23010, ld=0x7fffffffce30) at global/src/capi.c:1657

**Comment by jeffdaily** [comment]
Thank you for the detailed stack trace.  Unfortunately, this isn't just for NGA_Put64.  Looks like we broke the 32-bit limit for all comex implementations at our ARMCI compatibility layer.  I'm looking into a fix now.

**Comment by edoapra** [comment]
I believe that the old (pre-Comex) ARMCI infrastructure had the same 32-bit limit by design

**Comment by jeffdaily** [comment]
This is a new problem that was introduced recently, but yes, we've had 32/64-bit issues before.  This new issue occurs in a new check for contiguous buffers in otherwise strided communication.  I will add a check for overflow and if so, default back to the previous strided code path.

@edoapra and/or @ajmay81, do you happen to have small reproducer codes for these 32-bit limitations?  I'd like to add a test to our test suite and add it also to the CI testing.

**Comment by jeffdaily** [comment]
@ajmay81 I just committed 50b9ec20d86535e6de6bffd69a361d6653f4a5ad.  Please try your code again and let me know if it's working again.  Thanks.

**Comment by ajmay81** [comment]
I'm afraid it still fails with the same stack trace. I put the job in the debugger with break point at `armci_check_contiguous` where you made the changes so you can see how the program steps through that routine:

    Breakpoint 1, armci_check_contiguous (src_stride=0x7fffffffc864, dst_stride=0x7fffffffc884, count=0x7fffffffc844, n_stride=0) at src-armci/armci.c:33
    33        int ret = 1;
    (gdb) s
    34        int stridelen = 1;
    (gdb) s
    39        for (i=0; i<n_stride; i++) {
    (gdb) s
    52        return ret;
    (gdb) s
    53      }

The example I have is from Molpro code, which calls first Molpro and then PPIDD wrappers before it even gets to the call to GA. I can probably rip out a cut-down example eventually, but it of course involves a very large buffer, so I don't know if that would really be appropriate for a regular regression test?

My guess is somewhere an int64_t is cast to an int, and there must be some warning option to gcc to catch this, maybe `-Wconversion`?

**Comment by jeffhammond** [comment]
The Clang-specific flag `-Wshorten-64-to-32` covers the subset of GCC's `-Wconversion` that is relevant to this issue.  We made heavy use of it when working on MPICH large-count-safety.

However, I recall these flags do not help when integer truncation occurs as the result of an explicit cast.  But `-Wno-int-to-pointer-cast` and `-Wno-pointer-to-int-cast` might be useful for those cases.  My solution to the explicit cast problem for MPICH was just to remove all instances of casting to `int`.

At some point in the past, I tried to make GA count-safe, but I did not come close to finishing.  However, some of those patches can be seen in https://github.com/GlobalArrays/ga/pull/4/commits.

**Comment by jeffdaily** [comment]
@ajmay81 Would you mind trying one more thing for me?  In "comex/src-armci/armci.c" line 29, could you have the function armci_check_contiguous(...) always return 0 to disable the check and go back to our earlier implementation?

**Comment by ajmay81** [comment]
@jeffdaily I'm afraid that fails too going down the comex_puts route instead of comex_put:

    Program received signal SIGSEGV, Segmentation fault.
    (gdb) where
    #0  0x00007ffff296c254 in __memcpy_sse2_unaligned () from /lib64/libc.so.6
    #1  0x0000000003ada0a6 in _my_memcpy (dest=0x7ffdb1a86010, src=0x7ffecfc3a010, n=18446744071562067968) at src-mpi/comex.c:139
    #2  0x0000000003adaddd in _put_nbi (src=0x7ffecfc3a010, dst=0x7ffdb1a86010, bytes=-2147483648, proc=0) at src-mpi/comex.c:644
    #3  0x0000000003adb4e3 in comex_puts (src_ptr=0x7ffecfc3a010, src_stride_ar=0x7fffffffc8c4, dst_ptr=0x7ffdb1a86010, dst_stride_ar=0x7fffffffc8e4, count=0x7fffffffc8a4, stride_levels=0, proc=0, group=0) at src-mpi/comex.c:835
    #4  0x0000000003ad683c in PARMCI_PutS (src_ptr=0x7ffecfc3a010, src_stride_arr=0x7fffffffc8c4, dst_ptr=0x7ffdb1a86010, dst_stride_arr=0x7fffffffc8e4, count=0x7fffffffc8a4, stride_levels=0, proc=0) at src-armci/armci.c:472
    #5  0x0000000003ad971c in ARMCI_PutS (src_ptr=0x7ffecfc3a010, src_stride_arr=0x7fffffffc8c4, dst_ptr=0x7ffdb1a86010, dst_stride_arr=0x7fffffffc8e4, count=0x7fffffffc8a4, stride_levels=0, proc=0) at src-armci/capi.c:377
    #6  0x0000000003a53c79 in ngai_puts (loc_base_ptr=0x7ffecfc3a010 "", pbuf=0x7ffecfc3a010 "", stride_loc=0x7fffffffc8c4, prem=0x7ffdb1a86010 "", stride_rem=0x7fffffffc8e4, count=0x7fffffffc8a4, nstrides=0, proc=0, field_off=0, field_size=-1, type_size=8)
    at global/src/onesided.c:411
    #7  0x0000000003a56b9c in ngai_put_common (g_a=-1000, lo=0x7fffffffce30, hi=0x7fffffffcdf0, buf=0x7ffecfc3a010, ld=0x7fffffffcdb0, field_off=0, field_size=-1, nbhandle=0x0) at global/src/onesided.c:708
    #8  0x0000000003a59c8c in pnga_put (g_a=-1000, lo=0x7fffffffce30, hi=0x7fffffffcdf0, buf=0x7ffecfc3a010, ld=0x7fffffffcdb0) at global/src/onesided.c:1265
    #9  0x00000000039e1a3d in NGA_Put64 (g_a=-1000, lo=0x30937830, hi=0x30937870, buf=0x7ffecfc3a010, ld=0x7fffffffceb0) at global/src/capi.c:1657

**Comment by jeffdaily** [comment]
I was able to write a reproducer based on another "big" test we had in our global/testing directory.

```C
#include <stdio.h>
#include <stdlib.h>

#include "mp3.h"
#include "ga.h"
#include "macdecls.h"

/* create nproc by N matrix (int32 precision) */
#define N 2147483647 /* int32 max */

int main(int argc, char **argv)
{
    int me, nproc, g_a, ndim=1, type=MT_C_INT, *buf;
    int64_t dims[1], lo[1], hi[1];

    MP_INIT(argc,argv);
    GA_Initialize_ltd(-1);

    me=GA_Nodeid();
    nproc=GA_Nnodes();

    dims[0] = N*nproc;

    if(me==0) printf("Using %ld processes\n",(long)nproc);
    if(me==0) printf("memory = %ld bytes\n",((long)nproc)*((long)N)*4);

    g_a = NGA_Create64(type, ndim, dims, "A", NULL);

    GA_Zero(g_a);

    GA_Print_distribution(g_a);

    if(me == 0) {
        buf = (int*)(malloc(N*sizeof(int)));
        lo[0] = 0;
        hi[0] = N-1;
        NGA_Put64(g_a, lo, hi, buf, NULL);
    }

    GA_Sync();

    GA_Destroy(g_a);

    GA_Terminate();
    MP_FINALIZE();

    return 0;
}
```

`--with-openib` results

```bash
Using 4 processes
memory = 34359738352 bytes
3: WARNING:armci_set_mem_offset: offset changed 0 to -132902912
1: WARNING:armci_set_mem_offset: offset changed 0 to -132902912
Array Handle=-1000 Name:'A' Data Type:integer
Array Dimensions:8589934588
Process=0	 owns array section: [0:2147483646] 
Process=1	 owns array section: [2147483647:4294967293] 
Process=2	 owns array section: [4294967294:6442450940] 
Process=3	 owns array section: [6442450941:8589934587] 
```

`--with-mpi-mt` results

```bash
Using 4 processes
memory = 34359738352 bytes
Array Handle=-1000 Name:'A' Data Type:integer
Array Dimensions:8589934588
Process=0	 owns array section: [0:2147483646] 
Process=1	 owns array section: [2147483647:4294967293] 
Process=2	 owns array section: [4294967294:6442450940] 
Process=3	 owns array section: [6442450941:8589934587] 
[0] ../../comex/src-mpi-mt/comex.c:2971: nb_put: Assertion `bytes > 0' failed[0] Received an Error in Communication: (-1) comex_assert_fail
application called MPI_Abort(comm=0x84000004, -1) - process 0
```

`--with-mpi-ts` results

```bash
Using 4 processes
memory = 34359738352 bytes
Array Handle=-1000 Name:'A' Data Type:integer
Array Dimensions:8589934588
Process=0	 owns array section: [0:2147483646] 
Process=1	 owns array section: [2147483647:4294967293] 
Process=2	 owns array section: [4294967294:6442450940] 
Process=3	 owns array section: [6442450941:8589934587] 
[2:node016] unexpected disconnect completion event from [0:node015]
Fatal error in MPI_Iprobe: Internal MPI error!, error stack:
MPI_Iprobe(137)..........: MPI_Iprobe(src=MPI_ANY_SOURCE, tag=27624, comm=0x84000004, flag=0x7fffffffc498, status=0x7fffffffc464) failed
PMPIDI_CH3I_Progress(845): fail failed
(unknown)(): Internal MPI error!
```

`--with-mpi-pr` results

```bash
Using 2 processes
memory = 17179869176 bytes
Array Handle=-1000 Name:'A' Data Type:integer
Array Dimensions:4294967294
Process=0	 owns array section: [0:2147483646] 
Process=1	 owns array section: [2147483647:4294967293] 
[0] ../../comex/src-mpi-pr/comex.c:3999: nb_put: Assertion `bytes > 0' failed[0] Received an Error in Communication: (-1) comex_assert_fail
application called MPI_Abort(comm=0x84000004, -1) - process 0
```

### Summary

Clearly the comex ports are failing while the old ARMCI openib port does not.  TS was failing in a unique way because it is missing an assert that the size of a put must be positive.  I'm looking at fixing the comex ports now.

**Comment by jeffdaily** [comment]
My reproducer also fails for a single process.  I don't know if it exactly reproduces what @ajmay81  is seeing, but it's still showing a bug.  If you look at
https://github.com/GlobalArrays/ga/blob/9cb350ca70d163bd002de2012b000d2d7f9f80c6/global/src/onesided.c#L818
line 818 in onesided.c, you'll see where it overflows.  It is overflowing outside of comex, so this issue should be affecting both the old ARMCI as well as comex.  "count" is -4 for my reproducer.

**Comment by ajmay81** [comment]
@jeffdaily You're right, I just checked and openib silently corrupts, so perhaps the int64_t interface hasn't worked correctly for some time.

**Comment by bjpalmer** [comment]
I checked in a fix on the feature/iterator branch that may handle this problem (it gets past Jeff's reproducer). If the individual ARMCI/COMEX requests exceed the 2GByte threshold, they are decomposed into smaller blocks and sent individually. I've tested it in 1D but other problems start popping up if you try and create a 2D array with more than 2GBytes per node (GA_Zero crashes).

**Comment by ajaypanyala** [comment]
Resolved by Bruce a while ago!
